title: Santiago Bezchinsky # your name (or website title) here
logo: "/images/cv1.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Data Scientist | Python | Sociology | Music</strong> 
  <br><br>
  Data Scientist by day, musician by night
  <br><br>
  <a href="https://www.linkedin.com/in/santiago-bezchinsky/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-PD27JJ5W17 # your Google Analytics tracking ID here
